### ISSUE TITLE
Carousel Groups

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#130]
@halfempty 
Right now, the carousel only shows 2 groups (let's call them "A" and "B") of 3 images, with either A or B randomly loading when a user visits the site. We've tried adding a group "C" of 3 additional images, to increase the projects a user sees when they revisit the homepage - but it doesn't seem to be working.

**Comment by halfempty** [comment]
@gehalber They are really NOT supposed to be adding / editing fields!! It's possible for them to seriously break the site, and that's not something anyone wants. If the fields are not there, they need to talk to us about it, rather than messing around like this. Please strongly remind them to stop doing so.

I will investigate the request...

**Comment by halfempty** [comment]
@gehalber This is done

**Comment by gehalber** [comment]
@halfempty 
Ok. I'll do that. Thanks.
