### ISSUE TITLE
Slide Type: Animated

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#25]
Is this enabled? Can they do this?

**Comment by halfempty** [comment]
@gehalber We'd need to know where they'd want them, and make provision. The reason is, we don't usually show the exact version of the image they upload. Usually we have it pick one of the crops generated by WP. When a GIF is desired we'll need to be sure to use the original.

If GIFs are something they're serious about, I can brainstorm a couple of ways to achieve it, technically.

**Comment by gehalber** [comment]
ok. sounds good.
fyi, we maybe want to use those too on the ETC site  :)
or animated svgs. :)

**Comment by gehalber** [comment]
they say:
Used for a few special projects, same situation for youtube vids.

Should they add these in later and we’ll have a list of them with assets so you can sort and manage?

**Comment by halfempty** [comment]
Sounds good.

**Comment by halfempty** [comment]
@gehalber Looking at that file they sent over, I don't think GIF is the right format for this. The files are simply going to be too big to be useful on the web, no matter what.

My first instinct was to switch them to video. But seeing how they're using them, I'm thinking now this is something we can do using JPGs and JavaScript. Specifically, layer multiple JPGs on top of each other and then use JS to show/hide them on a timer. This could be managed in WP as a new slide type. 

I'll investigate how it might be handled. In the meantime, the client could prep JPGs representing each frame of the animation (using the same guidelines as before), and just keep them on his computer for now.

**Comment by gehalber** [comment]
Sounds good Marty.
