### ISSUE TITLE
Project Grid: Titles

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#50]
It looks like JSA is manually putting in all caps for these titles. I'm going to talk to them about this, but for the time being can you fix this in code so they're Title case?

**Comment by halfempty** [comment]
@gehalber Not sure I'm looking in the correct place, but it looks like the title case is caused by my css, rather than the client? And it looks like that's happening 'cause headings are set that way elsewhere, and the style is cascading down. So I've adjusted the CSS.

Reopen if it's not fixed or I've misundertood!

**Comment by gehalber** [comment]
perfect. Thanks!
