### ISSUE TITLE
Hyperlink colors

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#58]
In text, let make the hyperlinks: 2b67ff

In lists: first line should be #2b67ff; second line gray and hover to 2b67ff

**Comment by halfempty** [comment]
Okay, updated link colors in action here:

http://jsa.etc-nyc.com/research/new-media/
http://jsa.etc-nyc.com/exhibitions/

**Comment by gehalber** [comment]
Ok, these aren't right.
Can we try this: #6c6d6f

**Comment by halfempty** [comment]
Like so?

![image](https://cloud.githubusercontent.com/assets/775543/8642616/8e1598ae-28ec-11e5-96e6-727ee5b1705a.png)

**Comment by gehalber** [comment]
Another update to this. Can you make all the gray elements this color: #808285.

Also, I noticed that through our iterations we have a charcoal gray and a light gray happening, like here:
http://jsa.etc-nyc.com/exhibitions/

Let's make these both: #808285
On hover they should both change to Black.

Thanks!

**Comment by gehalber** [comment]
Oh, and also to underline! See jsa-design-20-website page 32.

<img width="634" alt="screen shot 2015-07-27 at 11 52 34 pm" src="https://cloud.githubusercontent.com/assets/6076488/8923129/bc2cf6fe-34ba-11e5-9c52-632b545afd02.png">

**Comment by halfempty** [comment]
@gehalber Okay, here's this:

![image](https://cloud.githubusercontent.com/assets/775543/8944789/44d912b6-3548-11e5-878e-b7e4781cce1d.png)
http://jsa.etc-nyc.com/exhibitions/

For paragraphs I've put the underline. However, our line-height's a bit tight for it, as you can see:

![image](https://cloud.githubusercontent.com/assets/775543/8944934/0c67ce80-3549-11e5-8a67-8bc7d6d04d55.png)
http://jsa.etc-nyc.com/profile/

Also, I'm noticing some inline styles to Justify the text:

![image](https://cloud.githubusercontent.com/assets/775543/8944983/5a86a852-3549-11e5-84b8-c6e80d0d9dc6.png)

Did y'all put this in, or the client? If it's an effect we want, it should be in the CSS rather than inline. Let me know if you'd like this converted.

**Comment by gehalber** [comment]
Is there a way to adjust the border-bottom distance or is that kind of fixed in?

JSA has been justifying the text just recently. I need to talk to them about that and I’ll let you know what they decide. If I get my way (no justification), can you override their inline styles?

g

**Comment by halfempty** [comment]
@gehalber In the context of paragraphs, where that border lands is baked-in. The other option is to use `text-decoration`, but it doesn't look the same:

![image](https://cloud.githubusercontent.com/assets/775543/8967106/a34e3922-35fa-11e5-851f-b24f07e7a20f.png)

Justifying: Unfortunately no. Since he's putting it right on the elements, that overrides what I specify in the stylesheet.

**Comment by gehalber** [comment]
Yeah, the underline isn’t working too well. Let’s kill it and see if we can final approval. Thanks!

**Comment by halfempty** [comment]
@gehalber Okay, line removed
