### ISSUE TITLE
Back to Projects button

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#61]
They want a "back to projects" that is in the info section button above the fold now. I'm having a hard time figuring out how to resolve this without cluttering up the header. If you have any ideas, I'm all ears!

**Comment by halfempty** [comment]
@gehalber Hmm. If you want to go back to all Projects, that link is there. But they're referring to the sub-category link that's currently at the bottom ("Back to Apartments & Lofts"), right?

I would probably try to just rearrange slightly, rather than introducing new elements. That is, put Projects and Research over on the right with About, News and Contact. And put Apartments & Lofts where Projects and Research currently is.

**Comment by gehalber** [comment]
That’s a nice idea. The only issue I see with that is if there was a project that belonged to two typologies and you entered the project from the other type it might be a little confusing. But maybe that’s over thinking it a bit.

**Comment by halfempty** [comment]
The way I coded it, the Back button only links to one category. If there's more than one I think it goes with whichever is first, alphabetically.
