### ISSUE TITLE
Various text style adjustments

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#66]
@gehalber Studying the comps, I'm picking up on a couple of tweaks. But maybe it would be possible for you to enumerate the changes, especially the overall ones? That would help a lot! Thank you!

**Comment by KyleETC** [comment]
Hey Marty, 

Geoff’s out of town this weekend skiing with buddies in Flagstaff, Arizona. I just took a look at the doc. and will highlight overall tweaks that jumped out below. Otherwise, I think Geoff did a nice job of breaking down each section within the doc. 

I am referencing the file: 
jsa-design-23-website-calibre-full.indd

Overall
Added a search icon to the nav on the top right
“Read more” Buttons are now smaller
They should now be 22 pt. vs. 26 pt.
Clean up styling — Inconsistent in certain areas, for instance: 
Contact — Note the spacing between Press Inquiries and the description. Need to tighten up these instances
Add a Subtitle style in text (See pg. 19) 
Hyperlinks within paragraphs (i.e: People descriptions, Articles (See pg. 19)
Static: Gray
Hover: Black with underline 
Hyperlinks and updated styling for the Archive section (See pg. 20)
Static: Black first line and gray second line
Hover: Underline the first line and the second line turns black
All other listings should be gray
Remove “Info” button from the project nav — this will now be the second slide in the project scroll/click through
Add back to top button on all project pages

Let me know if you have any additional questions. 

Thank you, 
Kyle

**Comment by gehalber** [comment]
Hi Marty,

Thanks KB. I think that covers pretty much everything. Couple notes: we don't need the search icon. No search functionality on site. 

Can you make a superscript style for citations? Not mandatory if difficult. See article page.

**Comment by halfempty** [comment]
@KyleETC @gehalber Thank you, this is very helpful.

For the link-hover decoration, normally I would use the `border` property, which gives a nice, sharp 1px line. But in this case our `line-height` is causing that to be a bit lower than really looks right. So I've used the `text-decoration` property, which puts the line closer to the letters (and is, strictly speaking, more semantically correct) but is rendering 2px thick. Please let me know if it stands out to you.

Aside from the Projects page, which I'll open a separate Issue for, I think these are done. Please take a look. Thanks!

**Comment by gehalber** [comment]
I think the underlining is feeling good. Thanks so much for taking a close look at that.

One note in the lists, we want to have the linkable items like this:

Static
First line: Black
Second line: Gray

On Hover
First line: Black with black underline
Second line: Black

![screen shot 2016-03-10 at 1 24 16 pm](https://cloud.githubusercontent.com/assets/6076488/13679877/0bfab192-e6c4-11e5-8eba-b90d7581efaf.png)

**Comment by gehalber** [comment]
Also, is there an elegant way we can style these footnotes in this article? There was a style we made in the design, but not sure if its easy on your end within the text editor...
![screen shot 2016-03-10 at 1 31 52 pm](https://cloud.githubusercontent.com/assets/6076488/13679967/78e803ea-e6c4-11e5-94e3-f7b1ad21c4ec.png)

**Comment by halfempty** [comment]
@gehalber List update in.

Moving Footnotes to its own issue for easier conversation...
